version: "3"
services:
  # ----- INGRESS APP -----
  ingress:
    container_name: nginx
    build:
      dockerfile: ./infra/ingress.dockerfile
      context: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal-network
    depends_on:
      # - backend
      - frontend

  # ----- FRONTEND -----
  frontend:
    container_name: frontend
    build:
      dockerfile: ./infra/frontend.dockerfile
      context: .
    restart: always
    networks:
      - internal-network

# ----- BACKEND -----
  backend:
    container_name: backend
    build:
      dockerfile: ./infra/backend.dockerfile
      context: .
    restart: always
    networks:
      - internal-network
    # volume for logs
    volumes:
      - source: ~/
        target: /deployments/logs
        type: bind

# ----- NETWORK -----
networks:
  internal-network:
    driver: bridge
